AllCops:
  TargetRubyVersion: "2.3"
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'example/**/*'

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Exclude:
    - 'spec/**/*'

# Configuration parameters: CountComments.
Metrics/ClassLength:
  CountComments: false
  Max: 500

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 30
  CountComments: false
  Exclude:
    - 'spec/**/*'

# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  CountComments: false
  Max: 30
  Exclude:
    - 'orca_api.gemspec'
    - 'spec/**/*'

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 130

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  CountKeywordArgs: false
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/AsciiComments:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: compact, expanded
Style/EmptyMethod:
  Enabled: false

# Configuration parameters: SupportedStyles, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: false

# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Enabled: false

# SupportedStyles: line_count_based, semantic, braces_for_chaining
# ProceduralMethods: benchmark, bm, bmbm, create, each_with_object, measure, new, realtime, tap, with_object
# FunctionalMethods: let, let!, subject, watch
# IgnoredMethods: lambda, proc, it
Style/BlockDelimiters:
  Enabled: false

# Configuration parameters: EnforcedStyleForMultiline, SupportedStylesForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInLiteral:
  Enabled: false

# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: both, prefix, postfix
Style/NegatedIf:
  Enabled: false

# Configuration parameters: SupportedStyles, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  Enabled: false

# Configuration parameters: MinSize, SupportedStyles.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: when_needed, always, never
Style/FrozenStringLiteralComment:
  Enabled: false

Security/Eval:
  Exclude:
    - 'spec/**/*'

Performance/StringReplacement:
  Enabled: false

# Configuration parameters: Strict.
Style/NumericLiterals:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: prefer_alias, prefer_alias_method
Style/Alias:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: braces, no_braces, context_dependent
Style/BracesAroundHashParameters:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: leading, trailing
Layout/DotPosition:
  Enabled: false
